config/routes.rb
Rails.application.routes.draw do
  resources :recent_articles
  resources :customer_testimonies
  resources :pricing_plans
  resources :service_packages
  resources :landingpage_items
  resources :featured_products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer_testimony.rb
class CustomerTestimony
  include Mongoid::Document
  include Mongoid::Timestamps
  field :testimony_logo, type: String
  field :testimony_detail, type: String
  field :testimony_cust_img, type: String
  field :testimony_cust_name, type: String
  field :testimony_cust_title, type: String
end

app/controllers/customer_testimonies_controller.rb
class CustomerTestimoniesController < ApplicationController
  before_action :set_customer_testimony, only: %i[ show edit update destroy ]

  # GET /customer_testimonies or /customer_testimonies.json
  def index
    @customer_testimonies = CustomerTestimony.all
  end

  # GET /customer_testimonies/1 or /customer_testimonies/1.json
  def show
  end

  # GET /customer_testimonies/new
  def new
    @customer_testimony = CustomerTestimony.new
  end

  # GET /customer_testimonies/1/edit
  def edit
  end

  # POST /customer_testimonies or /customer_testimonies.json
  def create
    @customer_testimony = CustomerTestimony.new(customer_testimony_params)

    respond_to do |format|
      if @customer_testimony.save
        format.html { redirect_to @customer_testimony, notice: "Customer testimony was successfully created." }
        format.json { render :show, status: :created, location: @customer_testimony }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer_testimony.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer_testimonies/1 or /customer_testimonies/1.json
  def update
    respond_to do |format|
      if @customer_testimony.update(customer_testimony_params)
        format.html { redirect_to @customer_testimony, notice: "Customer testimony was successfully updated." }
        format.json { render :show, status: :ok, location: @customer_testimony }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer_testimony.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_testimonies/1 or /customer_testimonies/1.json
  def destroy
    @customer_testimony.destroy
    respond_to do |format|
      format.html { redirect_to customer_testimonies_url, notice: "Customer testimony was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_testimony
      @customer_testimony = CustomerTestimony.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_testimony_params
      params.require(:customer_testimony).permit(:testimony_logo, :testimony_detail, :testimony_cust_img, :testimony_cust_name, :testimony_cust_title)
    end
end

app/helpers/customer_testimonies_helper.rb
module CustomerTestimoniesHelper
end

app/views/customer_testimonies/_form.html.erb
<%= form_with(model: customer_testimony, local: true) do |form| %>
  <% if customer_testimony.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer_testimony.errors.count, "error") %> prohibited this customer_testimony from being saved:</h2>

      <ul>
        <% customer_testimony.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :testimony_logo %>
    <%= form.text_field :testimony_logo %>
  </div>

  <div class="field">
    <%= form.label :testimony_detail %>
    <%= form.text_field :testimony_detail %>
  </div>

  <div class="field">
    <%= form.label :testimony_cust_img %>
    <%= form.text_field :testimony_cust_img %>
  </div>

  <div class="field">
    <%= form.label :testimony_cust_name %>
    <%= form.text_field :testimony_cust_name %>
  </div>

  <div class="field">
    <%= form.label :testimony_cust_title %>
    <%= form.text_field :testimony_cust_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customer_testimonies/edit.html.erb
<h1>Editing Customer Testimony</h1>

<%= render 'form', customer_testimony: @customer_testimony %>

<%= link_to 'Show', @customer_testimony %> |
<%= link_to 'Back', customer_testimonies_path %>

app/views/customer_testimonies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customer Testimonies</h1>

<table>
  <thead>
    <tr>
      <th>Testimony logo</th>
      <th>Testimony detail</th>
      <th>Testimony cust img</th>
      <th>Testimony cust name</th>
      <th>Testimony cust title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customer_testimonies.each do |customer_testimony| %>
      <tr>
        <td><%= customer_testimony.testimony_logo %></td>
        <td><%= customer_testimony.testimony_detail %></td>
        <td><%= customer_testimony.testimony_cust_img %></td>
        <td><%= customer_testimony.testimony_cust_name %></td>
        <td><%= customer_testimony.testimony_cust_title %></td>
        <td><%= link_to 'Show', customer_testimony %></td>
        <td><%= link_to 'Edit', edit_customer_testimony_path(customer_testimony) %></td>
        <td><%= link_to 'Destroy', customer_testimony, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer Testimony', new_customer_testimony_path %>

app/views/customer_testimonies/new.html.erb
<h1>New Customer Testimony</h1>

<%= render 'form', customer_testimony: @customer_testimony %>

<%= link_to 'Back', customer_testimonies_path %>

app/views/customer_testimonies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Testimony logo:</strong>
  <%= @customer_testimony.testimony_logo %>
</p>

<p>
  <strong>Testimony detail:</strong>
  <%= @customer_testimony.testimony_detail %>
</p>

<p>
  <strong>Testimony cust img:</strong>
  <%= @customer_testimony.testimony_cust_img %>
</p>

<p>
  <strong>Testimony cust name:</strong>
  <%= @customer_testimony.testimony_cust_name %>
</p>

<p>
  <strong>Testimony cust title:</strong>
  <%= @customer_testimony.testimony_cust_title %>
</p>

<%= link_to 'Edit', edit_customer_testimony_path(@customer_testimony) %> |
<%= link_to 'Back', customer_testimonies_path %>