config/routes.rb
Rails.application.routes.draw do
  resources :recent_articles
  resources :customer_testimonies
  resources :pricing_plans
  resources :service_packages
  resources :landingpage_items
  resources :featured_products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pricing_plan.rb
class PricingPlan
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :price, type: String
  field :description, type: String
end

app/controllers/pricing_plans_controller.rb
class PricingPlansController < ApplicationController
  before_action :set_pricing_plan, only: %i[ show edit update destroy ]

  # GET /pricing_plans or /pricing_plans.json
  def index
    @pricing_plans = PricingPlan.all
  end

  # GET /pricing_plans/1 or /pricing_plans/1.json
  def show
  end

  # GET /pricing_plans/new
  def new
    @pricing_plan = PricingPlan.new
  end

  # GET /pricing_plans/1/edit
  def edit
  end

  # POST /pricing_plans or /pricing_plans.json
  def create
    @pricing_plan = PricingPlan.new(pricing_plan_params)

    respond_to do |format|
      if @pricing_plan.save
        format.html { redirect_to @pricing_plan, notice: "Pricing plan was successfully created." }
        format.json { render :show, status: :created, location: @pricing_plan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pricing_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pricing_plans/1 or /pricing_plans/1.json
  def update
    respond_to do |format|
      if @pricing_plan.update(pricing_plan_params)
        format.html { redirect_to @pricing_plan, notice: "Pricing plan was successfully updated." }
        format.json { render :show, status: :ok, location: @pricing_plan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pricing_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pricing_plans/1 or /pricing_plans/1.json
  def destroy
    @pricing_plan.destroy
    respond_to do |format|
      format.html { redirect_to pricing_plans_url, notice: "Pricing plan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pricing_plan
      @pricing_plan = PricingPlan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pricing_plan_params
      params.require(:pricing_plan).permit(:title, :price, :description)
    end
end

app/helpers/pricing_plans_helper.rb
module PricingPlansHelper
end

app/views/pricing_plans/_form.html.erb
<%= form_with(model: pricing_plan, local: true) do |form| %>
  <% if pricing_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pricing_plan.errors.count, "error") %> prohibited this pricing_plan from being saved:</h2>

      <ul>
        <% pricing_plan.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pricing_plans/edit.html.erb
<h1>Editing Pricing Plan</h1>

<%= render 'form', pricing_plan: @pricing_plan %>

<%= link_to 'Show', @pricing_plan %> |
<%= link_to 'Back', pricing_plans_path %>

app/views/pricing_plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pricing Plans</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pricing_plans.each do |pricing_plan| %>
      <tr>
        <td><%= pricing_plan.title %></td>
        <td><%= pricing_plan.price %></td>
        <td><%= pricing_plan.description %></td>
        <td><%= link_to 'Show', pricing_plan %></td>
        <td><%= link_to 'Edit', edit_pricing_plan_path(pricing_plan) %></td>
        <td><%= link_to 'Destroy', pricing_plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pricing Plan', new_pricing_plan_path %>

app/views/pricing_plans/new.html.erb
<h1>New Pricing Plan</h1>

<%= render 'form', pricing_plan: @pricing_plan %>

<%= link_to 'Back', pricing_plans_path %>

app/views/pricing_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @pricing_plan.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @pricing_plan.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pricing_plan.description %>
</p>

<%= link_to 'Edit', edit_pricing_plan_path(@pricing_plan) %> |
<%= link_to 'Back', pricing_plans_path %>