config/routes.rb
Rails.application.routes.draw do
  resources :recent_articles
  resources :customer_testimonies
  resources :pricing_plans
  resources :service_packages
  resources :landingpage_items
  resources :featured_products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recent_article.rb
class RecentArticle
  include Mongoid::Document
  include Mongoid::Timestamps
  field :article_img, type: String
  field :publication_date, type: String
  field :publisher, type: String
  field :title, type: String
end

app/controllers/recent_articles_controller.rb
class RecentArticlesController < ApplicationController
  before_action :set_recent_article, only: %i[ show edit update destroy ]

  # GET /recent_articles or /recent_articles.json
  def index
    @recent_articles = RecentArticle.all
  end

  # GET /recent_articles/1 or /recent_articles/1.json
  def show
  end

  # GET /recent_articles/new
  def new
    @recent_article = RecentArticle.new
  end

  # GET /recent_articles/1/edit
  def edit
  end

  # POST /recent_articles or /recent_articles.json
  def create
    @recent_article = RecentArticle.new(recent_article_params)

    respond_to do |format|
      if @recent_article.save
        format.html { redirect_to @recent_article, notice: "Recent article was successfully created." }
        format.json { render :show, status: :created, location: @recent_article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recent_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recent_articles/1 or /recent_articles/1.json
  def update
    respond_to do |format|
      if @recent_article.update(recent_article_params)
        format.html { redirect_to @recent_article, notice: "Recent article was successfully updated." }
        format.json { render :show, status: :ok, location: @recent_article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recent_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recent_articles/1 or /recent_articles/1.json
  def destroy
    @recent_article.destroy
    respond_to do |format|
      format.html { redirect_to recent_articles_url, notice: "Recent article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recent_article
      @recent_article = RecentArticle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recent_article_params
      params.require(:recent_article).permit(:article_img, :publication_date, :publisher, :title)
    end
end

app/helpers/recent_articles_helper.rb
module RecentArticlesHelper
end

app/views/recent_articles/_form.html.erb
<%= form_with(model: recent_article, local: true) do |form| %>
  <% if recent_article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recent_article.errors.count, "error") %> prohibited this recent_article from being saved:</h2>

      <ul>
        <% recent_article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :article_img %>
    <%= form.text_field :article_img %>
  </div>

  <div class="field">
    <%= form.label :publication_date %>
    <%= form.text_field :publication_date %>
  </div>

  <div class="field">
    <%= form.label :publisher %>
    <%= form.text_field :publisher %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recent_articles/edit.html.erb
<h1>Editing Recent Article</h1>

<%= render 'form', recent_article: @recent_article %>

<%= link_to 'Show', @recent_article %> |
<%= link_to 'Back', recent_articles_path %>

app/views/recent_articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recent Articles</h1>

<table>
  <thead>
    <tr>
      <th>Article img</th>
      <th>Publication date</th>
      <th>Publisher</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recent_articles.each do |recent_article| %>
      <tr>
        <td><%= recent_article.article_img %></td>
        <td><%= recent_article.publication_date %></td>
        <td><%= recent_article.publisher %></td>
        <td><%= recent_article.title %></td>
        <td><%= link_to 'Show', recent_article %></td>
        <td><%= link_to 'Edit', edit_recent_article_path(recent_article) %></td>
        <td><%= link_to 'Destroy', recent_article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recent Article', new_recent_article_path %>

app/views/recent_articles/new.html.erb
<h1>New Recent Article</h1>

<%= render 'form', recent_article: @recent_article %>

<%= link_to 'Back', recent_articles_path %>

app/views/recent_articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article img:</strong>
  <%= @recent_article.article_img %>
</p>

<p>
  <strong>Publication date:</strong>
  <%= @recent_article.publication_date %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @recent_article.publisher %>
</p>

<p>
  <strong>Title:</strong>
  <%= @recent_article.title %>
</p>

<%= link_to 'Edit', edit_recent_article_path(@recent_article) %> |
<%= link_to 'Back', recent_articles_path %>