config/routes.rb
Rails.application.routes.draw do
  resources :recent_articles
  resources :customer_testimonies
  resources :pricing_plans
  resources :service_packages
  resources :landingpage_items
  resources :featured_products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/landingpage_item.rb
class LandingpageItem
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :description, type: String
  field :price, type: String
  field :rating, type: String
end

app/controllers/landingpage_items_controller.rb
class LandingpageItemsController < ApplicationController
  before_action :set_landingpage_item, only: %i[ show edit update destroy ]

  # GET /landingpage_items or /landingpage_items.json
  def index
    @landingpage_items = LandingpageItem.all
  end

  # GET /landingpage_items/1 or /landingpage_items/1.json
  def show
  end

  # GET /landingpage_items/new
  def new
    @landingpage_item = LandingpageItem.new
  end

  # GET /landingpage_items/1/edit
  def edit
  end

  # POST /landingpage_items or /landingpage_items.json
  def create
    @landingpage_item = LandingpageItem.new(landingpage_item_params)

    respond_to do |format|
      if @landingpage_item.save
        format.html { redirect_to @landingpage_item, notice: "Landingpage item was successfully created." }
        format.json { render :show, status: :created, location: @landingpage_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @landingpage_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /landingpage_items/1 or /landingpage_items/1.json
  def update
    respond_to do |format|
      if @landingpage_item.update(landingpage_item_params)
        format.html { redirect_to @landingpage_item, notice: "Landingpage item was successfully updated." }
        format.json { render :show, status: :ok, location: @landingpage_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @landingpage_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /landingpage_items/1 or /landingpage_items/1.json
  def destroy
    @landingpage_item.destroy
    respond_to do |format|
      format.html { redirect_to landingpage_items_url, notice: "Landingpage item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_landingpage_item
      @landingpage_item = LandingpageItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def landingpage_item_params
      params.require(:landingpage_item).permit(:name, :description, :price, :rating)
    end
end

app/helpers/landingpage_items_helper.rb
module LandingpageItemsHelper
end

app/views/landingpage_items/_form.html.erb
<%= form_with(model: landingpage_item, local: true) do |form| %>
  <% if landingpage_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(landingpage_item.errors.count, "error") %> prohibited this landingpage_item from being saved:</h2>

      <ul>
        <% landingpage_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/landingpage_items/edit.html.erb
<h1>Editing Landingpage Item</h1>

<%= render 'form', landingpage_item: @landingpage_item %>

<%= link_to 'Show', @landingpage_item %> |
<%= link_to 'Back', landingpage_items_path %>

app/views/landingpage_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Landingpage Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @landingpage_items.each do |landingpage_item| %>
      <tr>
        <td><%= landingpage_item.name %></td>
        <td><%= landingpage_item.description %></td>
        <td><%= landingpage_item.price %></td>
        <td><%= landingpage_item.rating %></td>
        <td><%= link_to 'Show', landingpage_item %></td>
        <td><%= link_to 'Edit', edit_landingpage_item_path(landingpage_item) %></td>
        <td><%= link_to 'Destroy', landingpage_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Landingpage Item', new_landingpage_item_path %>

app/views/landingpage_items/new.html.erb
<h1>New Landingpage Item</h1>

<%= render 'form', landingpage_item: @landingpage_item %>

<%= link_to 'Back', landingpage_items_path %>

app/views/landingpage_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @landingpage_item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @landingpage_item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @landingpage_item.price %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @landingpage_item.rating %>
</p>

<%= link_to 'Edit', edit_landingpage_item_path(@landingpage_item) %> |
<%= link_to 'Back', landingpage_items_path %>